services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: guzamak
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: pnpm run start